// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pick_new_bugs
NumericVector pick_new_bugs(NumericVector arr, int size, bool replace, NumericVector prob);
RcppExport SEXP _dilgrowth_pick_new_bugs(SEXP arrSEXP, SEXP sizeSEXP, SEXP replaceSEXP, SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type replace(replaceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(pick_new_bugs(arr, size, replace, prob));
    return rcpp_result_gen;
END_RCPP
}
// growth_one_group
NumericVector growth_one_group(NumericVector this_timestep, double grow_step, Rcpp::Nullable<Rcpp::NumericMatrix> interactions);
RcppExport SEXP _dilgrowth_growth_one_group(SEXP this_timestepSEXP, SEXP grow_stepSEXP, SEXP interactionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type this_timestep(this_timestepSEXP);
    Rcpp::traits::input_parameter< double >::type grow_step(grow_stepSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type interactions(interactionsSEXP);
    rcpp_result_gen = Rcpp::wrap(growth_one_group(this_timestep, grow_step, interactions));
    return rcpp_result_gen;
END_RCPP
}
// growth
NumericVector growth(NumericVector x, NumericVector carrying_capacities, int grow_step, Rcpp::Nullable<Rcpp::NumericMatrix> interactions);
RcppExport SEXP _dilgrowth_growth(SEXP xSEXP, SEXP carrying_capacitiesSEXP, SEXP grow_stepSEXP, SEXP interactionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type carrying_capacities(carrying_capacitiesSEXP);
    Rcpp::traits::input_parameter< int >::type grow_step(grow_stepSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type interactions(interactionsSEXP);
    rcpp_result_gen = Rcpp::wrap(growth(x, carrying_capacities, grow_step, interactions));
    return rcpp_result_gen;
END_RCPP
}
// growth_log
NumericVector growth_log(NumericVector x, NumericVector carrying_capacities, Rcpp::Nullable<Rcpp::NumericMatrix> interactions);
RcppExport SEXP _dilgrowth_growth_log(SEXP xSEXP, SEXP carrying_capacitiesSEXP, SEXP interactionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type carrying_capacities(carrying_capacitiesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type interactions(interactionsSEXP);
    rcpp_result_gen = Rcpp::wrap(growth_log(x, carrying_capacities, interactions));
    return rcpp_result_gen;
END_RCPP
}
// check_step
int check_step(NumericVector this_timestep, int abun_total, double grow_step, bool is_grow_step_a_perc);
RcppExport SEXP _dilgrowth_check_step(SEXP this_timestepSEXP, SEXP abun_totalSEXP, SEXP grow_stepSEXP, SEXP is_grow_step_a_percSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type this_timestep(this_timestepSEXP);
    Rcpp::traits::input_parameter< int >::type abun_total(abun_totalSEXP);
    Rcpp::traits::input_parameter< double >::type grow_step(grow_stepSEXP);
    Rcpp::traits::input_parameter< bool >::type is_grow_step_a_perc(is_grow_step_a_percSEXP);
    rcpp_result_gen = Rcpp::wrap(check_step(this_timestep, abun_total, grow_step, is_grow_step_a_perc));
    return rcpp_result_gen;
END_RCPP
}
// full_growth
NumericVector full_growth(NumericVector this_timestep, int abun_total, int grow_step, bool is_grow_step_a_perc, String func, Rcpp::Nullable<Rcpp::NumericMatrix> interactions, Rcpp::Nullable<Rcpp::NumericVector> carrying_capacities);
RcppExport SEXP _dilgrowth_full_growth(SEXP this_timestepSEXP, SEXP abun_totalSEXP, SEXP grow_stepSEXP, SEXP is_grow_step_a_percSEXP, SEXP funcSEXP, SEXP interactionsSEXP, SEXP carrying_capacitiesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type this_timestep(this_timestepSEXP);
    Rcpp::traits::input_parameter< int >::type abun_total(abun_totalSEXP);
    Rcpp::traits::input_parameter< int >::type grow_step(grow_stepSEXP);
    Rcpp::traits::input_parameter< bool >::type is_grow_step_a_perc(is_grow_step_a_percSEXP);
    Rcpp::traits::input_parameter< String >::type func(funcSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type interactions(interactionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type carrying_capacities(carrying_capacitiesSEXP);
    rcpp_result_gen = Rcpp::wrap(full_growth(this_timestep, abun_total, grow_step, is_grow_step_a_perc, func, interactions, carrying_capacities));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dilgrowth_pick_new_bugs", (DL_FUNC) &_dilgrowth_pick_new_bugs, 4},
    {"_dilgrowth_growth_one_group", (DL_FUNC) &_dilgrowth_growth_one_group, 3},
    {"_dilgrowth_growth", (DL_FUNC) &_dilgrowth_growth, 4},
    {"_dilgrowth_growth_log", (DL_FUNC) &_dilgrowth_growth_log, 3},
    {"_dilgrowth_check_step", (DL_FUNC) &_dilgrowth_check_step, 4},
    {"_dilgrowth_full_growth", (DL_FUNC) &_dilgrowth_full_growth, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_dilgrowth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
