# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pick_new_bugs <- function(x, size, replace, prob) {
    .Call(`_dilgrowth_pick_new_bugs`, x, size, replace, prob)
}

#' @export
growth <- function(this_timestep, abun_total, grow_step) {
    .Call(`_dilgrowth_growth`, this_timestep, abun_total, grow_step)
}

#' @export
full_growth <- function(this_timestep, abun_total, grow_step) {
    .Call(`_dilgrowth_full_growth`, this_timestep, abun_total, grow_step)
}

#' @export
growth_with_interactions <- function(this_timestep, abun_total, grow_step, interactions) {
    .Call(`_dilgrowth_growth_with_interactions`, this_timestep, abun_total, grow_step, interactions)
}

